server.port=8080
spring.application.name=payment-hub-backend

spring.datasource.url=jdbc:h2:mem:paymenthub;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
